config/routes.rb
Rails.application.routes.draw do
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  root "welcome#index"

  constraints(SubdomainRouter) do
    get '/' => 'channels#show', as: :subdomain_show
  end
  
  get 'welcome/index'
  get 'welcome/contact'

  namespace :api, path: "", constraints: {subdomain: 'api'}, defaults: {format: 'json'} do
    namespace :v1 do
      get '/channel'        => 'channel#show'
      post '/create_wager'  => 'wagers#create_wager'
      post '/set_winner'    => 'wagers#set_winner'
    end
  end

  resources :channels do
    resources :wagers do
      get 'realtime'    => 'wagers#process_realtime', as: :realtime
      get 'render_form' => 'wagers#render_form',      as: :render_form, on: :collection
      post 'setup'      => 'wagers#new_wager_setup',  as: :setup,       on: :collection
      post 'winner/:wager_option_id'     => 'wagers#distribute_winnings', as: :winner, on: :member
    end

    get  'active'       => 'channels#active_wager', as: :active
    get 'game_search'  => 'channels#game_search' , as: :game_search,  on: :collection
    post 'unset_search' => 'channels#unset_search', as: :unset_search, on: :collection
  end

  # THESE NEED NESTING UNDER APPROPRIATE RESOURCES:
  post '/place_bet' => 'wagers#place_bet', as: :place_bet

  resources :games do
    get 'info' => 'games#game_info', as: :info, on: :member
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show] do
    get  "auth"    => 'users#auth',         as: :auth,   on: :collection
    post "api_key" => "users#generate_key", as: :api_key
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base

  acts_as_url :name, url_attribute: :slug

  has_many :balances
  has_many :wagers

  def self.parse_channels(streams)
    stream_data = []
    streams.to_a.each_with_index do |stream, i|
      channel = stream['channel']
      stream_data[i] = { 
        display_name: channel['display_name'],
        viewers: channel['viewers'],
        status: channel['status'],
        preview: stream['preview'],
        name: channel['name'],
        game: channel['game']
      }
    end
    stream_data
  end

  def to_param
    name
  end

end

app/controllers/api/v1/channel_controller.rb
class API::V1::ChannelController < API::V1::ApiController

  before_filter :authenticate

  # GET /channel
  # Returns the user's channel
  def show
    respond_with @user.channel.to_json(except: [:user_id, :slug])
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!

  def index
    if cookies.signed[:last_search].present?
      streams = twitch.search_streams(query: cookies.signed[:last_search])
      @streams = Channel.parse_channels(streams[:body]["streams"]) rescue nil
    end

    @streams = Channel.parse_channels(twitch.streams[:body]["streams"]) if @streams.blank?
    @search_title = cookies.signed[:last_search].present? ? "Results for: #{cookies.signed[:last_search]}" : "Popular Channels"

    games = twitch.top_games
    if games.present?
      @games = games[:body]["top"].map{ |game| game["game"]["name"] }
    end
  end

  def game_search
    streams = twitch.search_streams(query: params[:game_name])
    @streams = Channel.parse_channels(streams[:body]["streams"]) rescue nil

    respond_to do |format|
      if @streams.present?
        @search_title = params[:game_name].present? ? "Results for: #{params[:game_name]}" : "Popular Channels"
        cookies.signed[:last_search] = params[:game_name]
        format.js { render 'channelfield' }
      else
        format.js { render nothing: true }
      end
    end
  end

  def unset_search
    cookies.delete(:last_search) if cookies.signed[:last_search].present?
    redirect_to action: :index
  end


  def active_wager
    channel = Channel.find_by(name: params[:channel_id])
    @wager = Wager.find_by(channel_id: channel.id, active: true)
    
    respond_to do |format|
      if @wager.nil? || @wager.id.to_s == params[:current_wager]
        format.js { render nothing: true }
      else
        format.js { render 'betfield' }
      end
    end
  end

  def show
    Channel.find_or_create_by(name: params[:id])
    stream = twitch.stream(params[:id])

    # Get some stuff about the current Twitch state
    channel = twitch.channel(params[:id])
    @channel_data = {
      status: channel[:body]['status'],
      game: channel[:body]['game'],
      background: channel[:body]['background'],
      views: channel[:body]["views"]
    }

    raise_404 if stream[:response] == 404

    # Load or save this channel:
    @channel = Channel.find_by(name: params[:id])
    @balance = current_user.channel_balance(@channel)
    @wager = @channel.wagers.last
    if request.env['HTTP_USER_AGENT'] && request.env['HTTP_USER_AGENT'] [/(Mobile\/.+Safari)|(AppleWebKit\/.+Mobile)/]
      @player = 'hls_player'
    else
      @player = 'flash_player'
    end

    if @wager
      opt_ids = @wager.wager_options.map(&:id)
      @transaction = Transaction.find_by(user_id: current_user, wager_option_id: opt_ids)
    end
  end

  private

  def channel_not_found
    raise ActionController::RoutingError.new('Channel not found!')
  end
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/views/channels/_flash_player.html.haml
%object#live_embed_player_flash{type: "application/x-shockwave-flash", height: '400', width: '600', data:"http://www.twitch.tv/widgets/live_embed_player.swf?channel=#{channel}", bgcolor: '#000'}
  %param{name: 'allowFullScreen',   value: 'true'  }
  %param{name: 'allowScriptAccess', value: 'true'  }
  %param{name: 'allowNetworking',   value: 'all'   }
  %param{name: 'movie', value: 'http://www.twitch.tv/widgets/live_embed_player.swf' }
  %param{name: 'flashvars', value: "hostname=www.twitch.tv&channel=#{channel}&auto_play=true&start_volume=25"}

app/views/channels/_hls_player.html.haml
#player-wrapper
  #player
    %iframe{ type: "text/html", width: 620, height: 378, src: "http://twitch.tv/#{channel}/hls"}

app/views/channels/betfield.js.erb
$('#bet-field').html("<%= escape_javascript(render partial: 'channels/partials/bet_field', locals: { wager: @wager }) %>");

app/views/channels/channelfield.js.erb
$('#channel-list').html("<%= escape_javascript(render partial: 'channels/partials/channel_field', locals: { streams: @streams, search_title: @stream_title }) %>");

app/views/channels/index.html.haml
.col-sm-3
  .game-filter
    %h3 Trending Games
    .row
      = search_field "game-search", "", placeholder: 'Search', class: 'form-control game-search'
    %ul
      - @games.each do |game|
        %li= link_to game, "#", class: 'sidebar-game-item'
  .row
    - if @search_title != "Popular Channels"
      .col-xs-12.text-right
        = link_to "Clear Search", unset_search_channels_path, method: :post

.col-sm-9#channel-list
  = render 'channels/partials/channel_field', streams: @streams, search_title: @search_title

app/views/channels/show.html.haml
#channel-container
  - if @wager
    .row-ctr
      #bet-field
        = render 'channels/partials/bet_field', wager: @wager


  #left-col.left-row-only
    .row
      #player{data: {channel: @channel.name} }
        = render @player, channel: @channel.slug

    .row
      #channel-info
        .row
          #ci-left
            %i.fa.fa-gamepad
            .game-name= @channel_data[:game]
          #ci-right
            %i.fa.fa-user
              = " #{number_with_delimiter(@channel_data[:views], delimiter: ",")} Views"
        .row
          .col-xs-12
            %h3= @channel_data[:status]

        .row
          .col-xs-12
            = link_to "Toggle Chat", "#", class: "btn btn-looted pull-right", id: "toggle-chat"

  #right-row.col-xs-4.hidden
    .row
      %iframe.col-xs-10.col-xs-offset-1{frameborder: "0", scrolling: "no", id: "chat_embed",  src:"http://www.twitch.tv/#{@channel.name}/chat", height: "560", width: "100%"}


- if @wager.present? && current_user.present? 
  :javascript
    initIntervals("#{@wager.id if @wager}", "#{current_user.id}", "#{params[:id]}");

:javascript
  $("#toggle-chat").on("click", function(e) {
    e.preventDefault();
    if($("#left-col").hasClass("left-row-only")) {
      $("#left-col").removeClass("left-row-only");
      $("#left-col").addClass("left-row");
      $("#right-row").removeClass("hidden");
    } else {
      $("#left-col").removeClass("left-row");
      $("#left-col").addClass("left-row-only");
      $("#right-row").addClass("hidden");
    }
  })