config/routes.rb
Rails.application.routes.draw do
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  root "welcome#index"

  constraints(SubdomainRouter) do
    get '/' => 'channels#show', as: :subdomain_show
  end
  
  get 'welcome/index'
  get 'welcome/contact'

  namespace :api, path: "", constraints: {subdomain: 'api'}, defaults: {format: 'json'} do
    namespace :v1 do
      get '/channel'        => 'channel#show'
      post '/create_wager'  => 'wagers#create_wager'
      post '/set_winner'    => 'wagers#set_winner'
    end
  end

  resources :channels do
    resources :wagers do
      get 'realtime'    => 'wagers#process_realtime', as: :realtime
      get 'render_form' => 'wagers#render_form',      as: :render_form, on: :collection
      post 'setup'      => 'wagers#new_wager_setup',  as: :setup,       on: :collection
      post 'winner/:wager_option_id'     => 'wagers#distribute_winnings', as: :winner, on: :member
    end

    get  'active'       => 'channels#active_wager', as: :active
    get 'game_search'  => 'channels#game_search' , as: :game_search,  on: :collection
    post 'unset_search' => 'channels#unset_search', as: :unset_search, on: :collection
  end

  # THESE NEED NESTING UNDER APPROPRIATE RESOURCES:
  post '/place_bet' => 'wagers#place_bet', as: :place_bet

  resources :games do
    get 'info' => 'games#game_info', as: :info, on: :member
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show] do
    get  "auth"    => 'users#auth',         as: :auth,   on: :collection
    post "api_key" => "users#generate_key", as: :api_key
  end

end

app/models/wager.rb
class Wager < ActiveRecord::Base
  belongs_to :game
  belongs_to :channel

  has_many :wager_options

  accepts_nested_attributes_for :wager_options,
    reject_if: :all_blank, allow_destroy: true

  validates :game, :question, :min_amount, :max_amount, presence: true

  scope :active, -> { find_by(active: true) }

  def set_winner(option)

    if option and option.wager == self
      self.winning_option = option.id
      self.suspend

      one_pct = self.total_amount_bet * 0.01
      p "--- REVENUE FOR STREAMER + BETSTREAM: $#{one_pct}"

      # give the option to the game, let it grab the transactions
      redeposits = self.game.calculate_winnings(self, option) || []

      redeposits.each do |uid, amt|
        user = User.find(uid)
        balance = user.channel_balance(channel)
        balance.change(amt)
      end

      status = "Wager suspended, winnings distributed"
    end
  end

  def suspended?
    self.suspended_at.present? && self.active == false
  end

  def winner
    return self.winning_option.present? ? WagerOption.find(winning_option) : nil
  end

  def place_bet(wager_option_id, current_user, amount)
    amount = amount.to_i
    wager = WagerOption.find(wager_option_id).wager
    bal = current_user.channel_balance(wager.channel)

    if wager.blank?
      error_message = "Cannot find wager for that option!"
    elsif amount < wager.min_amount
      error_message = "Amount must be above $#{wager.min_amount.to_i}"
    elsif amount > wager.max_amount
      error_message = "Amount must be under $#{wager.max_amount.to_i}"
    elsif bal.balance - amount < 0
      error_message = "Not enough balance!"
    end

    if !error_message
      transaction = Transaction.create(
        amount: amount,
        wager_option_id: wager_option_id,
        user_id: current_user.id)

      bal.change(-amount)
      return { success: true, new_balance: bal.display_value }
    else
      return { success: false, error_message: error_message}
    end
  end

  def suspend
    self.active = false
    self.suspended_at = DateTime.now
    self.save
  end

  def latest_transaction
    options = self.wager_options.map(&:id)
    Transaction.where(wager_option_id: options).last
  end

  def user_transaction(user_id)
    Transaction.find_by(user_id: user_id,
      wager_option_id: self.wager_options.map(&:id))
  end

  # Return the total amount put up for this wager
  def total_amount_bet
    total_amount = 0
    self.wager_options.each do |wo|
      total_amount +=  wo.amount_bet
    end
    total_amount
  end

  # Return a general overview of what has been bet,
  # how much, etc
  def transaction_data
    transactions = []
    self.wager_options.each do |wo|
      option_data = {}

      transactions << {
        option: wo,
        transactions: wo.transactions,
        total_amount: wo.amount_bet,
        count: wo.transactions.count
      }
    end
    transactions
  end
    
end

app/controllers/api/v1/wagers_controller.rb
class API::V1::WagersController < API::V1::ApiController

  before_filter :authenticate
  before_action :set_wager

  # GET /channel/(/:id)/wager
  # Returns the channel's current wager
  def wager
    render json: @wager.to_json(except: [:id])
  end

  # POST /channel/(/:id)/create_wager
  def create_wager
    channel = @user.channel
    if channel.wagers.active.present?
      render json: { message: 'Wager already active.' } and return
    end

    if params[:wager].present?
      wager = Wager.new(wager_params)
      wager.channel_id = channel.id

      if wager.save
        render json: { message: 'Saved Wager successfully.' }
      else
        render json: { message: 'Failed to save Wager, is the data correct?.' }
      end

    else
      render json: { message: 'Your request was malformed or incomplete.'}
    end
  end

  # POST /set_winner
  def set_winner
    option = @wager.wager_options.find(params[:wager_option])
    if option.wager.channel == @user.channel
      message = option.wager.set_winner(option)
    else
      message = 'Failed to set winner for Wager.'
    end

    respond_to do |format|
      format.json { render json: { message: message }}
    end
  end


private

  # Use callbacks to share common setup or constraints between actions.
  def set_wager
    @channel = @user.channel
    return false if @channel.blank?

    @wager = @channel.wagers.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wager_params
    params.require(:wager).permit(:game_id, :channel_id, :question, :min_amount, :max_amount,
      wager_options_attributes: [:id, :text, :_destroy])
  end

end

app/controllers/wagers_controller.rb
class WagersController < ApplicationController
  before_action :set_channel, only: [
    :index, :place_bet, :distribute_winnings, :create, :show, :active_wager]

  before_action :set_wager, only: [
    :show, :place_bet, :edit, :update, :destroy, :distribute_winnings
  ]

  # GET /wagers
  # GET /wagers.json
  def index
    @active_wager = Wager.where(channel: @channel, active: true).last
    @last_wagers = Wager.where(channel: @channel, active: false).last(5)
  end

  def place_bet
    result = { success: false, error_message: "Can't find that wager option!"}
    option = @wager.wager_options.find(params[:wager_option_id])
    if option.present?
      result = @wager.place_bet(params[:wager_option_id], current_user, params[:amount])
    end
    render json: result
  end

  def distribute_winnings
    result = { success: false, error_message: "Can't find that wager option!"}
    
    option = @wager.wager_options.find(params[:wager_option_id])
    if option.present?
      result = { success: true, status: option.wager.set_winner(option) } 
    end

    respond_to do |format|
      format.html { redirect_to channel_wagers_path, notice: "Winner has been set, all bets have been paid out!"}
      format.json { render json: result }
    end
  end

  def process_realtime
    response = {}
    
    if @wager.present?
      if @wager.active
        odds_data = []
        @wager.wager_options.each do |option|
          odds_data << { id: option.id, value: option.calculate_odds }
        end
        response[:odds] = odds_data.as_json
      elsif params[:uid].present?
        transaction = @wager.user_transaction(params[:uid].to_i)
        if transaction
          response[:wager_state] = {
            state: transaction.wager_option.won ? "won" : "lost",
            winopt: @wager.winning_option,
            balance: current_user.channel_balance(@wager.channel).display_value
          }
        end
      end
    end

    render json: response
  end

  def new_wager_setup
    @wager = Wager.new
    2.times{ @wager.wager_options.build }

    game = Game.find(params[:game_id])
    raise_404 if !game.present?

    @game_name = game.name
    @max_options = game.max_options
    @wager.game = game

    render "wagers/game_forms/#{game.partial_name}"
  end

  # GET /wagers/1
  # GET /wagers/1.json
  def show
    @summary = @wager.transaction_data || []
  end

  # GET /wagers/new
  def new
    @games = Game.all
  end

  # GET /wagers/1/edit
  def edit
  end

  # POST /wagers
  # POST /wagers.json
  def create
    @games = Game.all
    @wager = Wager.new(wager_params)
    @wager.channel = @channel

    respond_to do |format|
      if @wager.save
        format.html { redirect_to @channel, notice: 'Wager was successfully created.' }
        format.json { render @wager, status: :created }
      else
        format.html { render "wagers/game_forms/#{@wager.game.partial_name}" }
        format.json { render json: @wager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wagers/1
  # PATCH/PUT /wagers/1.json
  def update
    respond_to do |format|
      if @wager.update(wager_params)
        format.html { redirect_to channel_wager_path(@channel, @wager), notice: 'Wager was successfully updated.' }
        format.json { render :show, status: :ok, location: @wager }
      else
        format.html { render :edit }
        format.json { render json: @wager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wagers/1
  # DELETE /wagers/1.json
  def destroy
    @wager.suspend
    respond_to do |format|
      format.html { redirect_to channel_url(@wager.channel), notice: 'Wager was successfully suspended.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wager
      @wager = @channel.wagers.find(params[:id])
    end

    def set_channel
      @channel = Channel.find_by(name: params[:channel_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wager_params
      params.require(:wager).permit(:game_id, :question, :min_amount, :max_amount,
        wager_options_attributes: [:id, :text, :_destroy])
    end
end

app/helpers/wagers_helper.rb
module WagersHelper

end

app/views/wagers/_form.html.haml
.help-block
  First, choose your wager type from the dropdown below. We'll show you a description of how each wager is played.

.game-selector-row
  .col-xs-3#game-infographic

  = simple_form_for "", url: setup_channel_wagers_path do |f|
    .col-xs-5#game-selector
      = f.input :game_id, as: :select, collection: @games, label_method: :name, value_method: :id, include_blank: false, label: false, class: 'form-control'
    .col-xs-3
      = f.submit "Choose", class: "btn btn-looted"

.well#game-description

:javascript
  var game_info = function() {

    var game_id = $('select#_game_id').val()
    $.ajax({
      url: '/games/'+game_id+'/info.json',
    }).success(function(data) {
      $("#game-description").text(data.description);
    });
  };

  $('select#_game_id').on('change', function() {
    game_info();
  });

  game_info();

app/views/wagers/_wager_option_fields.html.haml
.nested-fields.row
  .col-xs-11
    = f.input :text, placeholder: 'Betting Option', label: false
  .col-xs-1.btn-remove
    = link_to_remove_association f do
      %i.fa.fa-times.fa-2x

app/views/wagers/_wager_options_fields.html.haml
.nested-fields
  .col-xs-11
    = f.input :text, placeholder: 'Enter Option Text', label: false
  .col-xs-1.btn-remove
    = link_to_remove_association f do
      %i.fa.fa-times.fa-2x

app/views/wagers/edit.html.haml
.container-fluid
  %h3 Editing wager

  = render 'form'

  = link_to 'Show', channel_wagers_path(@channel, @wager)
  \|
  = link_to 'Back', wagers_path

app/views/wagers/index.html.haml
.wager-summary
  - if @active_wager
    .box
      %h3 Active Wager
      %table
        %tr
          %th Game Type
          %th Question
          %th Minimum Amount
          %th Maximum Amount
          %th
        %tr
          %td= @active_wager.game.name
          %td= @active_wager.question
          %td= number_to_currency(@active_wager.min_amount, unit: '$')
          %td= number_to_currency(@active_wager.max_amount, unit: '$')
          %td= link_to 'View', channel_wager_path(@channel, @active_wager)


  - if @last_wagers
    .box
      %h3 Wager History
      %table
        %tr
          %th Game Type
          %th Question
          %th Minimum Amount
          %th Maximum Amount
          %th

        - @last_wagers.each do |wager|
          %tr
            %td= wager.game.name
            %td= wager.question
            %td= number_to_currency(wager.min_amount, unit: '$')
            %td= number_to_currency(wager.max_amount, unit: '$')
            %td= link_to 'View', channel_wager_path(@channel, wager)
        %div{ class: "#{'wager-row' unless @last_wagers.present?}" }
      = link_to 'Back to channel', channel_path(params[:channel_id]), class: 'btn btn-default'
      = link_to 'New Wager', new_channel_wager_path, class: 'btn btn-looted', :disabled => @active_wager ? 'disabled' : nil
    
    %br
  - else
    .wager-row.box
      .panel.panel-warning
        .panel-heading
          %h3.panel-title Oh no! You don't have any wagers!
        .panel-body
          %p Let's fix that:
          %ul
            %li Check out an interactive guide on getting a wager running.
            %li
              = link_to new_channel_wager_path do
                = "Go to the wager creation page."

app/views/wagers/new.html.haml
.wager-input
  %h2 Create Wager
  = render 'form'

app/views/wagers/show.html.haml
.wager.wager-show{style: "margin-top: 50px;", class: "game-#{@wager.game.id}" }
  .row
    .col-xs-12
      %h2.title= @wager.question
        
  .row.options
    - @wager.wager_options.each do |option|
      .wager-option
        - if @wager.suspended?
          = link_to option.text, "#", class: "btn btn-wager-success btn-lg #{'btn-wager-winner' if @wager.suspended? && @wager.winner == option}", style: "background-color: #FFF"
        - else
          = button_to option.text, winner_channel_wager_path(@channel, @wager, option), class: "btn btn-wager-success btn-lg #{'btn-wager-winner' if @wager.suspended? && @wager.winner == option}", style: "background-color: #FFF"
        - if @wager.suspended?
          %h4
            %span.label.label-info
              = option.calculate_odds

  = link_to 'Back', channel_wagers_path(@wager.channel.name), class: 'btn btn-looted'