config/routes.rb
Rails.application.routes.draw do
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  root "welcome#index"

  constraints(SubdomainRouter) do
    get '/' => 'channels#show', as: :subdomain_show
  end
  
  get 'welcome/index'
  get 'welcome/contact'

  namespace :api, path: "", constraints: {subdomain: 'api'}, defaults: {format: 'json'} do
    namespace :v1 do
      get '/channel'        => 'channel#show'
      post '/create_wager'  => 'wagers#create_wager'
      post '/set_winner'    => 'wagers#set_winner'
    end
  end

  resources :channels do
    resources :wagers do
      get 'realtime'    => 'wagers#process_realtime', as: :realtime
      get 'render_form' => 'wagers#render_form',      as: :render_form, on: :collection
      post 'setup'      => 'wagers#new_wager_setup',  as: :setup,       on: :collection
      post 'winner/:wager_option_id'     => 'wagers#distribute_winnings', as: :winner, on: :member
    end

    get  'active'       => 'channels#active_wager', as: :active
    get 'game_search'  => 'channels#game_search' , as: :game_search,  on: :collection
    post 'unset_search' => 'channels#unset_search', as: :unset_search, on: :collection
  end

  # THESE NEED NESTING UNDER APPROPRIATE RESOURCES:
  post '/place_bet' => 'wagers#place_bet', as: :place_bet

  resources :games do
    get 'info' => 'games#game_info', as: :info, on: :member
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show] do
    get  "auth"    => 'users#auth',         as: :auth,   on: :collection
    post "api_key" => "users#generate_key", as: :api_key
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  def self.types
    %w(Roulette SimpleBet)
  end

  #validates :game_type, presence: true, inclusion: { in: self.types }

  def calculate_winnings(wager, winning_option)
    
    # Redeposit, win + original bet, to be recredited:
    redeposit_amounts = {}
    # get losing option
    losing_option = wager.wager_options.where
                    .not(id: winning_option.id).first

    return if losing_option.transactions.empty? && winning_option.transactions.empty?

    win_total = winning_option.amount_bet
    loss_total = losing_option.amount_bet

    total_pot = win_total + loss_total

    # find the share% of how much each is of the total
    win_share = (win_total/total_pot)
    loss_share = (loss_total/total_pot)
    one_pct = (total_pot / 100)

    host_share = (win_share+loss_share * one_pct)
    p "-- Host takes #{host_share}"

    win_total -= (win_share * one_pct)
    loss_total -= (loss_share * one_pct)

    winning_option.transactions.each do |win_trans|
      # Percentage of the total winning pot
      pot_percentage = (win_trans.amount / win_total).round(2)

      # Winnings are <pot_pct>% of the losing pot
      winnings = loss_total * pot_percentage
      redeposit_amount = (win_trans.amount + winnings)
      redeposit_amount -= win_share if !loss_total.zero?
      redeposit_amounts[win_trans.user.id] = redeposit_amount
      p "--- User #{win_trans.user.id} wins $#{winnings} on $#{win_trans.amount} bet"
    end

    redeposit_amounts
  end

  def partial_name
    self.game_type.tableize.singularize
  end
end

app/models/game/roulette.rb
class Roulette < Game

end

app/models/game/simple_bet.rb
class SimpleBet < Game

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :game_info]
  before_action :set_game_types, only: [:new, :edit]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = create_object

    if @game.save
      redirect_to games_path, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  # GET /games/1/info
  def game_info
    respond_to do |format|
      format.json { render json: @game }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def set_game_types
      @game_types = Game.descendants.map(&:name) rescue []
    end

    def create_object
      game_type = game_params[:game_type]
      if Game.types.include?(game_type)
        return game_type.constantize.new(game_params)
      else
        return Game.new(game_params)
      end
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:name, :max_options, :game_type, :description)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= simple_form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name

  .field
    = f.input :game_type, collection: Game.types, include_blank: false

  .field
    = f.input :description

  .field
    = f.input :max_options
  .actions.row{style: "margin-top: 25px;"}
    .col-xs-3
      = link_to 'Back', games_path, class: 'btn btn-default'
    .col-xs-2.pull-right
      = f.submit 'Save', class: 'btn btn-success pull-right'

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Listing games

%table.table.table-responsive
  %tr
    %th Name
    %th Max options
    %th Type
    %th Description
    %th
    %th
    %th

  - @games.each do |game|
    %tr
      %td= game.name
      %td= game.max_options
      %td= game.game_type
      %td= game.description
      %td= link_to 'Show', game_path(game)
      %td= link_to 'Edit', edit_game_path(game)
      %td= link_to 'Destroy', game_path(game), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1 New game

.row
  .col-xs-10.col-xs-offset-1.col-lg-6.col-lg-offset-3
    = render 'form'

app/views/games/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @game.name
%p
  %b Max options:
  = @game.max_options

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path