config/routes.rb
Rails.application.routes.draw do
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  root "welcome#index"

  constraints(SubdomainRouter) do
    get '/' => 'channels#show', as: :subdomain_show
  end
  
  get 'welcome/index'
  get 'welcome/contact'

  namespace :api, path: "", constraints: {subdomain: 'api'}, defaults: {format: 'json'} do
    namespace :v1 do
      get '/channel'        => 'channel#show'
      post '/create_wager'  => 'wagers#create_wager'
      post '/set_winner'    => 'wagers#set_winner'
    end
  end

  resources :channels do
    resources :wagers do
      get 'realtime'    => 'wagers#process_realtime', as: :realtime
      get 'render_form' => 'wagers#render_form',      as: :render_form, on: :collection
      post 'setup'      => 'wagers#new_wager_setup',  as: :setup,       on: :collection
      post 'winner/:wager_option_id'     => 'wagers#distribute_winnings', as: :winner, on: :member
    end

    get  'active'       => 'channels#active_wager', as: :active
    get 'game_search'  => 'channels#game_search' , as: :game_search,  on: :collection
    post 'unset_search' => 'channels#unset_search', as: :unset_search, on: :collection
  end

  # THESE NEED NESTING UNDER APPROPRIATE RESOURCES:
  post '/place_bet' => 'wagers#place_bet', as: :place_bet

  resources :games do
    get 'info' => 'games#game_info', as: :info, on: :member
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show] do
    get  "auth"    => 'users#auth',         as: :auth,   on: :collection
    post "api_key" => "users#generate_key", as: :api_key
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def twitch_auth(access_token)
    return @twitch_auth if @twitch_auth
    @twitch_auth = Twitch.new({access_token: access_token})
  end
  
  def twitch
    return @twitch if @twitch
    @twitch = Twitch.new({
      client_id: Rails.application.secrets.twitch_client_id,
      secret_key: Rails.application.secrets.twitch_secret_key,
      redirect_uri: root_url,
      scope: ["user_read", "channel_read"]
    })
  end

  protected

  def raise_404
    render file: "public/404.html", status: :not_found
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u|
      u.permit(:email, :access_token, :password, :password_confirmation)
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource_name
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def channel_view?
    current_page?(controller: "/channels", action: "show")
  end
    
end

app/views/application/_active_nav.html.haml
.collapse.navbar-collapse#navi-collapse
  %ul.nav.navbar-nav
    %li= link_to 'Games', channels_path
    %li= link_to 'Wagers', channel_wagers_path(params[:id]) if channel_view?
  %ul.nav.navbar-nav.navbar-right
    -if @channel && @balance
      %li#stream-balance
        = link_to "Stream Balance: #{number_to_currency(@balance.balance, unit: '$')}", '#'
    %li
      = link_to 'My Profile', user_path(id: current_user)
    %li.dropdown
      = link_to "#", "data-toggle" => "dropdown", role: "button", "aria-expanded" => false do
        %i.fa.fa-ellipsis-h
      %ul.dropdown-menu{role: "menu"}
        %li
          = link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/application/_flash_notices.html.haml
- if flash.now[:notice].present?
  .alert.alert-dismissible.alert-info{role: 'alert'}
    %button{type: 'alert', class: 'close', "data-dismiss" => "alert"}
      %span{"aria-hidden" => "true"}✖
    %strong Information
    %span= flash.now[:notice]
- if flash.now[:alert].present?
  .alert.alert-dismissible.alert-danger{role: 'alert'}
    %button{type: 'alert', class: 'close', "data-dismiss" => "alert"}
      %span{"aria-hidden" => "true"}✖
    %strong Error
    %span= flash.now[:alert]

app/views/application/_inactive_nav.html.haml
.collapse.navbar-collapse#navi-collapse
  %ul.nav.navbar-nav.navbar-right
    %li= link_to 'Home', root_path